# Generated by Django 6.0.2 on 2026-02-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
