# Generated by Django 6.0.2 on 2026-02-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers_company', '0002_alter_companyprofile_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(blank=True, default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_covers/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='founded_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='funding_stage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='one_liner_pitch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='work_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='CompanyVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='company_documents/')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='employers_company.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Verification Document',
                'verbose_name_plural': 'Company Verification Documents',
            },
        ),
    ]
