# Generated by Django 6.0 on 2026-03-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers_company', '0004_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='benefits',
            field=models.TextField(blank=True, help_text='Comma-separated list of active benefit labels'),
        ),
    ]
