# Generated by Django 6.0.2 on 2026-02-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_jobseekerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
